[workspace]
members = [
    "common",
    "compound-v2",
    "erc20",
    "erc20-price",
    "erc20-market-cap",
    "erc721",
    "substreams-helper",
    "uniswap-v2"
]

[profile.release]
lto = true
opt-level = 's'
strip = "debuginfo"