[package]
name = "substreams-common"
version = "0.1.0"
edition = "2021"

[dependencies]
ethabi = "17.0"
prost = "^0.11.0"
regex = "1.6.0"
substreams = "0.0.20"
substreams-ethereum = "0.2.2-rc.2"
thiserror = "1.0.35"
