name: Messari Substreams
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PROTOC: /usr/local/bin/protoc
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: install substreams cli
        uses: jaxxstorm/action-install-gh-release@v1.7.1
        with:
          repo: streamingfast/substreams
          cache: enable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: install buf
        uses: bufbuild/buf-setup-action@v1.7.0
      - name: install protoc
        env:
          PROTOC_ZIP: protoc-3.14.0-linux-x86_64.zip
        run: |
          curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/$PROTOC_ZIP
          sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
          sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
          rm -f $PROTOC_ZIP
          sudo chmod +x /usr/local/bin/protoc
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
            toolchain: stable
            target: wasm32-unknown-unknown
            override: true
            components: rustfmt, clippy
      - name: run cargo fmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: used cached Rust build artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            **/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: make erc20-price spkg
        run: make -C erc20-price build && make erc20-price-spkg
      - name: build all
        run: make build-all
      - name: Integrations
        run: make integrations-linux
