name: Messari Substreams
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PROTOC: /usr/local/bin/protoc
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: install substreams cli
        uses: jaxxstorm/action-install-gh-release@v1.7.1
        with:
          repo: streamingfast/substreams
          cache: enable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: request streaming fast authentication token
        run: |
          FIREHOSE_API_TOKEN=$(curl https://auth.dfuse.io/v1/auth/issue -s --data-binary '{"api_key":"${{secrets.STREAMING_FAST}}"}' | jq -r .token)
          echo "SUBSTREAMS_API_TOKEN=$FIREHOSE_API_TOKEN" >> $GITHUB_ENV
      - name: install buf
        uses: bufbuild/buf-setup-action@v1.7.0
      - name: install protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.14.0'
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
            toolchain: stable
            target: wasm32-unknown-unknown
            override: true
            components: rustfmt, clippy
      - name: run cargo fmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: used cached Rust build artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            **/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: make erc20-price spkg
        run: make -C erc20-price build && make erc20-price-spkg
      - name: build all
        run: make build-all
      - name: Integrations
        run: make integrations-linux
